// Copyright 2005 - 2009 - Morten Nielsen (www.sharpgis.net)
//
// This file is part of ProjNet.
// ProjNet is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// ProjNet is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with ProjNet; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy API naming retained for compatibility.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WGS84_UTM(System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Projections.MapProjection.Lon_origin")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Projections.MapProjection.Central_parallel")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Adjust_lon(System.Double)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Inv_mlfn(System.Double)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Qsfn(System.Double,System.Double,System.Double)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Sincos(System.Double,System.Double@,System.Double@)")]

[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Min")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Other")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Classic")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Geocentric")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Max")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Min")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Other")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Orthometric")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Ellipsoidal")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_AltitudeBarometric")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Normal")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_GeoidModelDerived")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Depth")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Max")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.LD_Min")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.LD_Max")]

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.CoordinateSystem")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.GeographicCoordinateSystem")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Wgs84ConversionInfo")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.IO.CoordinateSystems.WktStreamTokenizer")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.DatumTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GeocentricTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.PrimeMeridianTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.AlbersProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.KrovakProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.LambertAzimuthalEqualAreaProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.LambertConformalConic2SP")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.Mercator")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.MercatorAuxiliarySphere")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ObliqueStereographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.OrthographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PolarStereographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PolyconicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PseudoMercator")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.TransverseMercator")]

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Instance API shape is retained for compatibility and consistency with long-standing factory patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.CoordinateSystemFactory")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Instance API shape is retained for compatibility and consistency with long-standing factory patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.ParameterInfo")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Instance API shape is retained for compatibility and consistency with long-standing factory patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Projection implementation kept consistent with existing inheritance and override patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ObliqueStereographicProjection")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Projection implementation kept consistent with existing inheritance and override patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PolarStereographicProjection")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase canonicalization is intentional for EPSG/projection key matching and legacy compatibility.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ProjectionParameterSet")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase canonicalization is intentional for EPSG/projection key matching and legacy compatibility.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase canonicalization is intentional for EPSG/projection key matching and legacy compatibility.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ProjectionsRegistry")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Generated EPSG normalization intentionally uses lowercase aliases for stable map keys.", Scope = "type", Target = "~T:ProjNet.Data.Generated.EpsgCoordinateSystemFactory")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.IO.CoordinateSystems.StreamTokenizer")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.VerticalCoordinateSystem")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.HealpixProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.MapProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ObliqueStereographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PolarStereographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.AffineTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GeoTiffGridShiftMathTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GeoTiffGridLoader")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GtxVGridShiftMathTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.MathTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static members should appear before non-static members", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GeoTiffGridShiftMathTransform.Header")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "GeoTIFF grid transform and loader helpers are intentionally co-located for tightly coupled parsing/runtime behavior.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GeoTiffVGridShiftMathTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "GeoTIFF grid transform and loader helpers are intentionally co-located for tightly coupled parsing/runtime behavior.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GeoTiffGridLoader")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "GeoTIFF grid transform and loader helpers are intentionally co-located for tightly coupled parsing/runtime behavior.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.BaseGeoGrid")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "Grid resolver options remain co-located with resolver implementation for small internal resource-resolution API cohesion.", Scope = "type", Target = "~T:ProjNet.Resources.GridResourceResolverOptions")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1649:File name should match first type name", Justification = "Legacy multi-type source layout is intentionally retained to avoid large compatibility-risky file split churn.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.SampleEncoding")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1649:File name should match first type name", Justification = "Legacy file keeps interface and adapter definitions co-located for public API continuity.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.ICoordinateTransformationCore")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1649:File name should match first type name", Justification = "Legacy resource resolver file intentionally co-locates small support types with resolver implementation.", Scope = "type", Target = "~T:ProjNet.Resources.GridResourceResolutionMode")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1649:File name should match first type name", Justification = "Legacy resource resolver file intentionally co-locates small support types with resolver implementation.", Scope = "type", Target = "~T:ProjNet.Resources.IGridResourceFetchClient")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "Legacy matrix-style APIs and parsing shapes are retained for compatibility and readability.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.AffineTransform")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "Legacy matrix-style APIs and parsing shapes are retained for compatibility and readability.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.MathTransform")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "Legacy matrix-style APIs and parsing shapes are retained for compatibility and readability.", Scope = "type", Target = "~T:ProjNet.IO.CoordinateSystems.MathTransformWktReader")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "Legacy properties intentionally remain unavailable and preserve long-standing behavior for unsupported XML/WKT representations.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.FittedCoordinateSystem.XML")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "Legacy properties intentionally remain unavailable and preserve long-standing behavior for unsupported XML/WKT representations.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Transformations.AffineTransform.XML")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "Legacy properties intentionally remain unavailable and preserve long-standing behavior for unsupported XML/WKT representations.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Transformations.GeographicTransform.WKT")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "Legacy properties intentionally remain unavailable and preserve long-standing behavior for unsupported XML/WKT representations.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Transformations.GeographicTransform.XML")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "Legacy properties intentionally remain unavailable and preserve long-standing behavior for unsupported XML/WKT representations.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Unit.XML")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Invalid or unsupported WKT rows are intentionally skipped during bulk coordinate-system loading to preserve resilient legacy enumeration behavior.", Scope = "member", Target = "~M:ProjNet.CoordinateSystemServices.CreateCoordinateSystem(ProjNet.CoordinateSystems.CoordinateSystemFactory,System.String)~ProjNet.CoordinateSystems.CoordinateSystem")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Legacy API signatures are retained for compatibility with existing consumers and extension patterns.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Transformations.MathTransform.GetCodomainConvexHull(System.Collections.Generic.List{System.Double})")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Legacy API signatures are retained for compatibility with existing consumers and extension patterns.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Transformations.MathTransform.GetDomainFlags(System.Collections.Generic.List{System.Double})")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Legacy factory API signatures are retained for compatibility with existing consumers.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.CoordinateSystemFactory.CreateFittedCoordinateSystem(System.String,ProjNet.CoordinateSystems.CoordinateSystem,System.String,System.Collections.Generic.List{ProjNet.CoordinateSystems.AxisInfo})")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Legacy factory API signatures are retained for compatibility with existing consumers.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.CoordinateSystemFactory.CreateFittedCoordinateSystem(System.String,ProjNet.CoordinateSystems.CoordinateSystem,ProjNet.CoordinateSystems.Transformations.MathTransform,System.Collections.Generic.List{ProjNet.CoordinateSystems.AxisInfo})")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Legacy factory API signatures are retained for compatibility with existing consumers.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.CoordinateSystemFactory.CreateProjection(System.String,System.String,System.Collections.Generic.List{ProjNet.CoordinateSystems.ProjectionParameter})")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Projection parameter cloning keeps list semantics for compatibility with existing derived implementations.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.CloneParametersList(System.Collections.Generic.IEnumerable{ProjNet.CoordinateSystems.ProjectionParameter})")]
