// Copyright 2005 - 2009 - Morten Nielsen (www.sharpgis.net)
//
// This file is part of ProjNet.
// ProjNet is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// ProjNet is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with ProjNet; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy API naming retained for compatibility.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WGS84_UTM(System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Projections.MapProjection.Lon_origin")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~P:ProjNet.CoordinateSystems.Projections.MapProjection.Central_parallel")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Adjust_lon(System.Double)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Inv_mlfn(System.Double)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Qsfn(System.Double,System.Double,System.Double)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Legacy PROJ-derived helper naming retained in projection base class.", Scope = "member", Target = "~M:ProjNet.CoordinateSystems.Projections.MapProjection.Sincos(System.Double,System.Double@,System.Double@)")]

[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Min")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Other")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Classic")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Geocentric")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.HD_Max")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Min")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Other")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Orthometric")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Ellipsoidal")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_AltitudeBarometric")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Normal")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_GeoidModelDerived")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Depth")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.VD_Max")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.LD_Min")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Enum names are long-standing public API values.", Scope = "member", Target = "~F:ProjNet.CoordinateSystems.DatumType.LD_Max")]

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.CoordinateSystem")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.GeographicCoordinateSystem")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Wgs84ConversionInfo")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.IO.CoordinateSystems.WktStreamTokenizer")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.DatumTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.GeocentricTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.PrimeMeridianTransform")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.AlbersProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.KrovakProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.LambertAzimuthalEqualAreaProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.LambertConformalConic2SP")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.Mercator")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.MercatorAuxiliarySphere")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ObliqueStereographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.OrthographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PolarStereographicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PolyconicProjection")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PseudoMercator")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy member ordering is retained to avoid broad high-risk refactors.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.TransverseMercator")]

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Instance API shape is retained for compatibility and consistency with long-standing factory patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.CoordinateSystemFactory")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Instance API shape is retained for compatibility and consistency with long-standing factory patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.ParameterInfo")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Instance API shape is retained for compatibility and consistency with long-standing factory patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Projection implementation kept consistent with existing inheritance and override patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ObliqueStereographicProjection")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Projection implementation kept consistent with existing inheritance and override patterns.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.PolarStereographicProjection")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase canonicalization is intentional for EPSG/projection key matching and legacy compatibility.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ProjectionParameterSet")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase canonicalization is intentional for EPSG/projection key matching and legacy compatibility.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase canonicalization is intentional for EPSG/projection key matching and legacy compatibility.", Scope = "type", Target = "~T:ProjNet.CoordinateSystems.Projections.ProjectionsRegistry")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Generated EPSG normalization intentionally uses lowercase aliases for stable map keys.", Scope = "type", Target = "~T:ProjNet.Data.Generated.EpsgCoordinateSystemFactory")]
