<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Global tool packages applied to all projects -->
  <ItemGroup Label="Global Package References">
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
  </ItemGroup>

  <!-- Centrally managed package versions -->
  <ItemGroup Label="Library Packages">
    <PackageVersion Include="BitMiracle.LibTiff.NET" Version="2.4.660" />
    <PackageVersion Include="System.Memory" Version="4.6.0" />
    <PackageVersion Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup Label="Benchmark Packages">
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup Label="Test Packages">
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.5.2" />
    <PackageVersion Include="Npgsql" Version="10.0.2" />
    <PackageVersion Include="PublicApiGenerator" Version="11.5.4" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
</Project>
