using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy test member ordering retained to keep test churn low.", Scope = "type", Target = "~T:ProjNET.Tests.CoordinateTransformTests")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Legacy test member ordering retained to keep test churn low.", Scope = "type", Target = "~T:ProjNET.Tests.CoordinateTransformTestsBase")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test helper shape is retained to minimize churn in legacy test fixtures.", Scope = "type", Target = "~T:ProjNET.Tests.CoordinateTransformTestsBase")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test helper shape is retained to minimize churn in legacy test fixtures.", Scope = "type", Target = "~T:ProjNET.Tests.SharpMapIssues")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test helper shape is retained to minimize churn in legacy test fixtures.", Scope = "type", Target = "~T:ProjNET.Tests.WKT.WKTCoordSysParserTests")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Theory member data can legitimately provide null sentinel rows; null handling is intentional in fixture pipeline.", Scope = "member", Target = "~M:ProjNET.Tests.GieBuiltinsTheoryTests.BuiltinsCasesForImplementedProjectionsStayWithinTolerance(System.Object)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Theory member data can legitimately provide null sentinel rows; null handling is intentional in fixture pipeline.", Scope = "member", Target = "~M:ProjNET.Tests.GieBuiltinsTheoryTests.MoreBuiltinsCasesForImplementedProjectionsStayWithinTolerance(System.Object)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Theory member data can legitimately provide null sentinel rows; null handling is intentional in fixture pipeline.", Scope = "member", Target = "~M:ProjNET.Tests.GieBuiltinsTheoryTests.DhdnEtrs89CasesForImplementedProjectionsStayWithinTolerance(System.Object)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Theory member data can legitimately provide null sentinel rows; null handling is intentional in fixture pipeline.", Scope = "member", Target = "~M:ProjNET.Tests.GieBuiltinsTheoryTests.RemainingGieCasesForImplementedProjectionsStayWithinTolerance(System.Object)")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase canonicalization is intentional in WKT equivalence normalization helpers.", Scope = "type", Target = "~T:ProjNET.Tests.EpsgWktEquivalenceTheoryTests")]
