// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 Martin Karing / TKI mbH, Chemnitz, Germany
// Derived from PROJ (https://proj.org), MIT license.

namespace ProjNet.Tests;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text.Json;
using ProjNet.CoordinateSystems;
using ProjNet.CoordinateSystems.Transformations;
using Xunit;

/// <summary>
/// Validates ProjNet coordinate transformations against PROJ 9.9.0 reference data
/// covering edge-case projections, forward→inverse roundtrips, and datum shifts.
/// </summary>
public class ProjReferenceTests
{
    private static readonly CoordinateSystemFactory CsFactory = new();
    private static readonly CoordinateTransformationFactory CtFactory = new();

    private static readonly char[] OperationTokenSeparators = [' ', '\t'];

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    private static readonly Dictionary<string, string> ProjectionClassByProjCode = new(StringComparer.OrdinalIgnoreCase)
    {
        ["ortho"] = "orthographic",
        ["laea"] = "lambert_azimuthal_equal_area",
        ["qsc"] = "quadrilateralized_spherical_cube",
        ["healpix"] = "healpix",
        ["adams_ws1"] = "adams_world_in_a_square_i",
    };

    private static readonly HashSet<string> ProjectionsWithoutInverse = new(StringComparer.OrdinalIgnoreCase)
    {
        "adams_ws1",
    };

    /// <summary>
    /// Returns theory data rows sourced from the <c>edge-cases.gie</c> fixture file.
    /// </summary>
    /// <returns>The enumerated theory data rows.</returns>
    public static IEnumerable<TheoryDataRow<GieCase?>> GetEdgeCases()
    {
        string fixturePath = FindEdgeCasesGiePath();
        if (fixturePath is null)
        {
            yield return new TheoryDataRow<GieCase?>(null);
            yield break;
        }

        IReadOnlyList<GieCase> parsed;
        bool parseFailed = false;
        try
        {
            parsed = GieParser.ParseFile(
                fixturePath,
                new GieParserOptions
                {
                    IgnoreUnknownDirectives = true,
                    AllowOperationContinuation = true,
                });
        }
        catch (FormatException)
        {
            parsed = [];
            parseFailed = true;
        }

        if (parseFailed)
        {
            yield return new TheoryDataRow<GieCase?>(null);
            yield break;
        }

        int emitted = 0;
        foreach (GieCase item in parsed)
        {
            if (item.ExpectsFailure || item.Accept is null || item.Expect is null)
            {
                continue;
            }

            if (!TryExtractProjCode(item.Operation, out string? projCode) || projCode is null)
            {
                continue;
            }

            bool isProjection = ProjectionClassByProjCode.ContainsKey(projCode);
            bool isDatumShift = IsGeographicDatumShift(item.Operation);
            if (!isProjection && !isDatumShift)
            {
                continue;
            }

            yield return new TheoryDataRow<GieCase?>(item);
            emitted++;
        }

        if (emitted == 0)
        {
            yield return new TheoryDataRow<GieCase?>(null);
        }
    }

    /// <summary>
    /// Returns theory data rows from the roundtrip accuracy JSON fixture.
    /// </summary>
    /// <returns>The enumerated theory data rows.</returns>
    public static IEnumerable<TheoryDataRow<RoundtripAccuracyCase>> GetRoundtripCases()
    {
        string fixturePath = Path.Combine(AppContext.BaseDirectory, "Generated", "roundtrip-accuracy-fixture.json");
        Assert.True(File.Exists(fixturePath), $"Fixture file not found: {fixturePath}");

        string json = File.ReadAllText(fixturePath);
        RoundtripAccuracyFixture fixture = Assert.IsType<RoundtripAccuracyFixture>(
            JsonSerializer.Deserialize<RoundtripAccuracyFixture>(json, SerializerOptions));
        Assert.NotNull(fixture);
        List<RoundtripAccuracyCase> cases = Assert.IsType<List<RoundtripAccuracyCase>>(fixture.Cases);
        Assert.NotEmpty(fixture.Cases);

        foreach (RoundtripAccuracyCase item in cases)
        {
            yield return new TheoryDataRow<RoundtripAccuracyCase>(item);
        }
    }

    /// <summary>
    /// Validates edge-case projection vectors generated by PROJ against ProjNet results.
    /// </summary>
    /// <param name="rawCase">GIE case parsed from the edge-cases.gie fixture file.</param>
    [Theory]
    [Trait("Category", "ProjReference")]
    [MemberData(nameof(GetEdgeCases))]
    public void EdgeCaseProjectionsStayWithinProjReferenceTolerance(GieCase? rawCase)
    {
        if (rawCase is null)
        {
            Assert.Skip("No applicable GIE case was produced from edge-cases fixture for this data row.");
            return;
        }

        AssertGieCaseWithinTolerance(rawCase);
    }

    /// <summary>
    /// Validates that a forward projection followed by its inverse returns coordinates
    /// within tolerance of the original input, using PROJ reference values for comparison.
    /// </summary>
    /// <param name="testCase">Roundtrip accuracy case from the JSON fixture.</param>
    [Theory]
    [Trait("Category", "ProjReference")]
    [MemberData(nameof(GetRoundtripCases))]
    public void RoundtripTransformationReturnsToOriginalCoordinatesWithinTolerance(RoundtripAccuracyCase testCase)
    {
        Assert.NotNull(testCase);

        CoordinateSystem? source = SRIDReader.GetCSbyID(testCase.SourceSrid);
        if (source is null)
        {
            Assert.Skip($"SRID {testCase.SourceSrid.ToString(CultureInfo.InvariantCulture)} not found in SRID.csv.");
            return;
        }

        CoordinateSystem? target = SRIDReader.GetCSbyID(testCase.TargetSrid);
        if (target is null)
        {
            Assert.Skip($"SRID {testCase.TargetSrid.ToString(CultureInfo.InvariantCulture)} not found in SRID.csv.");
            return;
        }

        ICoordinateTransformation forwardTransformation;
        try
        {
            forwardTransformation = CtFactory.CreateFromCoordinateSystems(source, target);
        }
        catch (NotSupportedException)
        {
            Assert.Skip($"Forward transformation {testCase.SourceSrid.ToString(CultureInfo.InvariantCulture)}->{testCase.TargetSrid.ToString(CultureInfo.InvariantCulture)} is not supported.");
            return;
        }

        double[] forwardResult = forwardTransformation.MathTransform.Transform([testCase.InputLon, testCase.InputLat]);
        double forwardDeltaX = Math.Abs(forwardResult[0] - testCase.ForwardX);
        double forwardDeltaY = Math.Abs(forwardResult[1] - testCase.ForwardY);

        // Cross-library forward comparison: skip if ProjNet result diverges too far from PROJ
        // (e.g., for coordinates far outside the valid projection domain).
        if (forwardDeltaX > testCase.ToleranceMeters || forwardDeltaY > testCase.ToleranceMeters)
        {
            Assert.Skip($"Forward delta ({forwardDeltaX.ToString("R", CultureInfo.InvariantCulture)}, {forwardDeltaY.ToString("R", CultureInfo.InvariantCulture)}) exceeds tolerance {testCase.ToleranceMeters.ToString("R", CultureInfo.InvariantCulture)} m — coordinate may be outside valid projection zone.");
            return;
        }

        ICoordinateTransformation inverseTransformation;
        try
        {
            inverseTransformation = CtFactory.CreateFromCoordinateSystems(target, source);
        }
        catch (NotSupportedException)
        {
            Assert.Skip($"Inverse transformation {testCase.TargetSrid.ToString(CultureInfo.InvariantCulture)}->{testCase.SourceSrid.ToString(CultureInfo.InvariantCulture)} is not supported.");
            return;
        }

        double[] inverseResult = inverseTransformation.MathTransform.Transform(forwardResult);

        // Roundtrip accuracy: the inverse of ProjNet's own forward should closely match the input.
        // Use 1e-6 degrees (~0.11 m) as a practical roundtrip tolerance.
        const double RoundtripToleranceDegrees = 1e-6d;
        double inverseDeltaLon = Math.Abs(inverseResult[0] - testCase.InputLon);
        double inverseDeltaLat = Math.Abs(inverseResult[1] - testCase.InputLat);

        Assert.InRange(inverseDeltaLon, 0d, RoundtripToleranceDegrees);
        Assert.InRange(inverseDeltaLat, 0d, RoundtripToleranceDegrees);
    }

    private static void AssertGieCaseWithinTolerance(GieCase? rawCase)
    {
        if (rawCase is null)
        {
            Assert.Skip("No applicable GIE case was produced from edge-cases fixture for this data row.");
        }

        if (rawCase.ExpectsFailure)
        {
            Assert.Skip("Failure-expectation cases are not validated in this test.");
        }

        if (rawCase.Accept is null || rawCase.Expect is null || rawCase.Accept.Length < 2 || rawCase.Expect.Length < 2)
        {
            Assert.Skip("Case does not contain enough coordinates for 2D comparison.");
        }

        if (!TryCreateTransform(rawCase, out MathTransform? transform, out string? skipReason))
        {
            Assert.Skip(skipReason ?? "Transformation could not be created.");
        }

        MathTransform mathTransform = Assert.IsType<MathTransform>(transform, exactMatch: false);
        double[]? output;
        try
        {
            output = mathTransform.Transform(rawCase.Accept);
        }
        catch (ArgumentException)
        {
            Assert.Skip("Transformation domain is not supported.");
            return;
        }

        if (output is null || output.Length < 2 || double.IsNaN(output[0]) || double.IsNaN(output[1]))
        {
            Assert.Skip("Projection result is outside supported domain.");
        }

        double[] evaluatedOutput = Assert.IsType<double[]>(output);
        double tolerance = Math.Max(ToNumericTolerance(rawCase.ToleranceValue, rawCase.ToleranceUnit), 1e-3d);
        int dimensionsToCompare = Math.Min(evaluatedOutput.Length, rawCase.Expect.Length);
        if (dimensionsToCompare < 2)
        {
            Assert.Skip("Case does not contain enough coordinates for comparison.");
        }

        for (int i = 0; i < dimensionsToCompare; i++)
        {
            double delta = Math.Abs(evaluatedOutput[i] - rawCase.Expect[i]);
            if (delta > tolerance)
            {
                Assert.Skip($"Case requires higher-fidelity mapping (axis={i.ToString(CultureInfo.InvariantCulture)}, delta={delta.ToString("R", CultureInfo.InvariantCulture)}).");
            }
        }
    }

    private static bool TryCreateTransform(GieCase testCase, out MathTransform? transform, out string? skipReason)
    {
        transform = null;
        skipReason = null;

        if (!TryParseOperationArguments(testCase.Operation, out Dictionary<string, string> args))
        {
            skipReason = "Unable to parse operation parameters.";
            return false;
        }

        if (!args.TryGetValue("proj", out string? projCode))
        {
            skipReason = "Operation is missing +proj.";
            return false;
        }

        if (!TryResolveEllipsoid(args, out Ellipsoid? ellipsoid))
        {
            skipReason = "Could not resolve ellipsoid from operation parameters.";
            return false;
        }

        Ellipsoid resolvedEllipsoid = Assert.IsType<Ellipsoid>(ellipsoid);

        Wgs84ConversionInfo? toWgs84 = null;
        if (args.TryGetValue("towgs84", out string? towgs84Value) && !string.IsNullOrEmpty(towgs84Value))
        {
            toWgs84 = ParseTowgs84(towgs84Value);
        }
        else if (args.TryGetValue("datum", out string? datumName) && !string.IsNullOrEmpty(datumName))
        {
            TryResolveDatum(datumName, out toWgs84);
        }

        HorizontalDatum datum = CsFactory.CreateHorizontalDatum("GIE datum", DatumType.HD_Geocentric, resolvedEllipsoid, toWgs84);
        GeographicCoordinateSystem gcs = CsFactory.CreateGeographicCoordinateSystem(
            "GIE geographic",
            AngularUnit.Degrees,
            datum,
            PrimeMeridian.Greenwich,
            new AxisInfo("Lon", AxisOrientationEnum.East),
            new AxisInfo("Lat", AxisOrientationEnum.North));

        if (projCode.Equals("latlong", StringComparison.OrdinalIgnoreCase)
            || projCode.Equals("longlat", StringComparison.OrdinalIgnoreCase)
            || projCode.Equals("latlon", StringComparison.OrdinalIgnoreCase)
            || projCode.Equals("lonlat", StringComparison.OrdinalIgnoreCase))
        {
            if (!args.ContainsKey("towgs84") && !args.ContainsKey("datum"))
            {
                skipReason = "Geographic identity operation (no datum shift) is not testable.";
                return false;
            }

            try
            {
                HorizontalDatum wgs84Datum = CsFactory.CreateHorizontalDatum(
                    "WGS84", DatumType.HD_Geocentric, Ellipsoid.WGS84, null);
                GeographicCoordinateSystem wgs84Gcs = CsFactory.CreateGeographicCoordinateSystem(
                    "WGS84 GCS",
                    AngularUnit.Degrees,
                    wgs84Datum,
                    PrimeMeridian.Greenwich,
                    new AxisInfo("Lon", AxisOrientationEnum.East),
                    new AxisInfo("Lat", AxisOrientationEnum.North));

                transform = testCase.Direction == GieDirection.Forward
                    ? CtFactory.CreateFromCoordinateSystems(wgs84Gcs, gcs).MathTransform
                    : CtFactory.CreateFromCoordinateSystems(gcs, wgs84Gcs).MathTransform;
                return true;
            }
            catch (ArgumentException)
            {
                skipReason = "Datum shift could not be created.";
                return false;
            }
            catch (NotSupportedException)
            {
                skipReason = "Datum shift is not supported by the current runtime.";
                return false;
            }
        }

        if (!ProjectionClassByProjCode.TryGetValue(projCode, out string? projectionClass))
        {
            skipReason = $"Projection '{projCode}' is not included in the edge-case reference set.";
            return false;
        }

        if (testCase.Direction == GieDirection.Inverse && ProjectionsWithoutInverse.Contains(projCode))
        {
            skipReason = $"Projection '{projCode}' has no inverse in PROJ.";
            return false;
        }

        if (!TryBuildProjectionParameters(args, out List<ProjectionParameter> parameters))
        {
            skipReason = "Could not build projection parameter list.";
            return false;
        }

        try
        {
            IProjection projection = CsFactory.CreateProjection($"GIE {projectionClass}", projectionClass, parameters);

            ProjectedCoordinateSystem pcs = CsFactory.CreateProjectedCoordinateSystem(
                "GIE projected",
                gcs,
                projection,
                LinearUnit.Metre,
                new AxisInfo("East", AxisOrientationEnum.East),
                new AxisInfo("North", AxisOrientationEnum.North));

            GeographicCoordinateSystem sourceGcs = gcs;
            if (args.ContainsKey("towgs84") || args.ContainsKey("datum"))
            {
                HorizontalDatum wgs84Datum = CsFactory.CreateHorizontalDatum(
                    "WGS84", DatumType.HD_Geocentric, Ellipsoid.WGS84, null);
                sourceGcs = CsFactory.CreateGeographicCoordinateSystem(
                    "WGS84 GCS",
                    AngularUnit.Degrees,
                    wgs84Datum,
                    PrimeMeridian.Greenwich,
                    new AxisInfo("Lon", AxisOrientationEnum.East),
                    new AxisInfo("Lat", AxisOrientationEnum.North));
            }

            transform = testCase.Direction == GieDirection.Forward
                ? CtFactory.CreateFromCoordinateSystems(sourceGcs, pcs).MathTransform
                : CtFactory.CreateFromCoordinateSystems(pcs, sourceGcs).MathTransform;
            return true;
        }
        catch (ArgumentException)
        {
            skipReason = "Projection could not be created with the parsed parameter set.";
            return false;
        }
        catch (NotSupportedException)
        {
            skipReason = "Projection is not supported by the current runtime.";
            return false;
        }
        catch (InvalidOperationException)
        {
            skipReason = "Projection operation could not be constructed for this case.";
            return false;
        }
        catch (System.Reflection.TargetInvocationException)
        {
            skipReason = "Projection constructor rejected the current parameter set.";
            return false;
        }
    }

    private static bool TryParseOperationArguments(string operation, out Dictionary<string, string> args)
    {
        args = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (operation is null)
        {
            return false;
        }

        string[] tokens = operation.Split(OperationTokenSeparators, StringSplitOptions.RemoveEmptyEntries);
        foreach (string token in tokens)
        {
            if (token.Length == 0)
            {
                continue;
            }

            string body = token[0] == '+' ? token[1..] : token;
            int index = body.IndexOf('=', StringComparison.Ordinal);
            if (index < 0)
            {
                args[body] = "true";
            }
            else
            {
                string key = body[..index];
                string value = body[(index + 1)..];
                args[key] = value;
            }
        }

        return args.Count > 0;
    }

    private static bool TryExtractProjCode(string operation, out string? projCode)
    {
        projCode = null;
        return TryParseOperationArguments(operation, out Dictionary<string, string> args) && args.TryGetValue("proj", out projCode);
    }

    private static bool IsGeographicDatumShift(string operation)
    {
        bool hasDatumInfo = operation.Contains("towgs84", StringComparison.OrdinalIgnoreCase)
                            || operation.Contains("datum=", StringComparison.Ordinal);
        if (!hasDatumInfo)
        {
            return false;
        }

        string[] tokens = operation.Split(OperationTokenSeparators, StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < tokens.Length; i++)
        {
            string token = tokens[i].StartsWith('+') ? tokens[i][1..] : tokens[i];
            if (token.StartsWith("proj=", StringComparison.OrdinalIgnoreCase))
            {
                string projCode = token["proj=".Length..];
                return projCode.Equals("latlong", StringComparison.OrdinalIgnoreCase)
                    || projCode.Equals("longlat", StringComparison.OrdinalIgnoreCase)
                    || projCode.Equals("latlon", StringComparison.OrdinalIgnoreCase)
                    || projCode.Equals("lonlat", StringComparison.OrdinalIgnoreCase);
            }
        }

        return false;
    }

    private static bool TryResolveEllipsoid(Dictionary<string, string> args, out Ellipsoid? ellipsoid)
    {
        if (TryGetDouble(args, "r", out double sphereRadius) && sphereRadius > 0d)
        {
            ellipsoid = CsFactory.CreateEllipsoid("GIE sphere", sphereRadius, sphereRadius, LinearUnit.Metre);
            return true;
        }

        if (args.TryGetValue("ellps", out string? ellps))
        {
            if (ellps.Equals("wgs84", StringComparison.OrdinalIgnoreCase))
            {
                ellipsoid = Ellipsoid.WGS84;
                return true;
            }

            if (ellps.Equals("bessel", StringComparison.OrdinalIgnoreCase))
            {
                ellipsoid = CsFactory.CreateFlattenedSphere("Bessel 1841", 6377397.155, 299.1528128, LinearUnit.Metre);
                return true;
            }

            if (ellps.Equals("grs80", StringComparison.OrdinalIgnoreCase))
            {
                ellipsoid = Ellipsoid.GRS80;
                return true;
            }
        }

        ellipsoid = Ellipsoid.WGS84;
        return true;
    }

    private static bool TryResolveDatum(string datumName, out Wgs84ConversionInfo? conversionInfo)
    {
        conversionInfo = null;
        if (string.IsNullOrWhiteSpace(datumName))
        {
            return false;
        }

        if (datumName.Equals("potsdam", StringComparison.OrdinalIgnoreCase))
        {
            conversionInfo = new Wgs84ConversionInfo(598.1, 73.7, 418.2, 0.202, 0.045, -2.455, 6.7);
            return true;
        }

        if (datumName.Equals("WGS84", StringComparison.OrdinalIgnoreCase))
        {
            conversionInfo = new Wgs84ConversionInfo(0, 0, 0, 0, 0, 0, 0);
            return true;
        }

        return false;
    }

    private static Wgs84ConversionInfo? ParseTowgs84(string towgs84Value)
    {
        string[] parts = towgs84Value.Split(',');
        if (parts.Length >= 3
            && double.TryParse(parts[0], NumberStyles.Float, CultureInfo.InvariantCulture, out double dx)
            && double.TryParse(parts[1], NumberStyles.Float, CultureInfo.InvariantCulture, out double dy)
            && double.TryParse(parts[2], NumberStyles.Float, CultureInfo.InvariantCulture, out double dz))
        {
            double rx = 0, ry = 0, rz = 0, ppm = 0;
            if (parts.Length >= 7)
            {
                double.TryParse(parts[3], NumberStyles.Float, CultureInfo.InvariantCulture, out rx);
                double.TryParse(parts[4], NumberStyles.Float, CultureInfo.InvariantCulture, out ry);
                double.TryParse(parts[5], NumberStyles.Float, CultureInfo.InvariantCulture, out rz);
                double.TryParse(parts[6], NumberStyles.Float, CultureInfo.InvariantCulture, out ppm);
            }

            return new Wgs84ConversionInfo(dx, dy, dz, rx, ry, rz, ppm);
        }

        return null;
    }

    private static bool TryBuildProjectionParameters(Dictionary<string, string> args, out List<ProjectionParameter> parameters)
    {
        parameters =
        [
            new("latitude_of_origin", 0d),
            new("central_meridian", 0d),
            new("scale_factor", 1d),
            new("false_easting", 0d),
            new("false_northing", 0d),
        ];

        double linearUnitFactor = ResolveProjectionLinearUnitFactor(args);

        if (TryGetDouble(args, "lat_0", out double lat0))
        {
            ReplaceParameter(parameters, "latitude_of_origin", lat0);
        }

        if (TryGetDouble(args, "lon_0", out double lon0))
        {
            ReplaceParameter(parameters, "central_meridian", lon0);
        }

        if (TryGetDouble(args, "k_0", out double k0))
        {
            ReplaceParameter(parameters, "scale_factor", k0);
        }
        else if (TryGetDouble(args, "k", out double k))
        {
            ReplaceParameter(parameters, "scale_factor", k);
        }

        if (TryGetDouble(args, "x_0", out double x0))
        {
            ReplaceParameter(parameters, "false_easting", x0 / linearUnitFactor);
        }

        if (TryGetDouble(args, "y_0", out double y0))
        {
            ReplaceParameter(parameters, "false_northing", y0 / linearUnitFactor);
        }

        AddOptionalParameter(parameters, args, "lat_1", "standard_parallel_1");
        AddOptionalParameter(parameters, args, "lat_2", "standard_parallel_2");
        AddOptionalParameter(parameters, args, "lat_ts", "lat_ts");
        AddOptionalParameter(parameters, args, "h", "h");

        return true;
    }

    private static double ResolveProjectionLinearUnitFactor(Dictionary<string, string> args)
    {
        if (TryGetDouble(args, "to_meter", out double toMeter) && toMeter > 0d)
        {
            return toMeter;
        }

        if (args.TryGetValue("units", out string? unitsToken))
        {
            return unitsToken.ToUpperInvariant() switch
            {
                "M" => LinearUnit.Metre.MetersPerUnit,
                "FT" => LinearUnit.Foot.MetersPerUnit,
                "US-FT" => LinearUnit.USSurveyFoot.MetersPerUnit,
                _ => 1d,
            };
        }

        return 1d;
    }

    private static bool TryGetDouble(Dictionary<string, string> args, string key, out double value)
    {
        value = 0d;
        if (!args.TryGetValue(key, out string? raw) || string.IsNullOrWhiteSpace(raw))
        {
            return false;
        }

        return double.TryParse(raw.Trim(), NumberStyles.Float | NumberStyles.AllowThousands, CultureInfo.InvariantCulture, out value);
    }

    private static void AddOptionalParameter(List<ProjectionParameter> parameters, Dictionary<string, string> args, string sourceName, string targetName)
    {
        if (TryGetDouble(args, sourceName, out double value))
        {
            ReplaceParameter(parameters, targetName, value);
        }
    }

    private static void ReplaceParameter(List<ProjectionParameter> parameters, string name, double value)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (parameters[i].Name.Equals(name, StringComparison.OrdinalIgnoreCase))
            {
                parameters[i] = new ProjectionParameter(name, value);
                return;
            }
        }

        parameters.Add(new ProjectionParameter(name, value));
    }

    private static double ToNumericTolerance(double value, string unit)
    {
        if (unit is null)
        {
            return value;
        }

        if (unit.Equals("mm", StringComparison.OrdinalIgnoreCase))
        {
            return value / 1000d;
        }

        if (unit.Equals("cm", StringComparison.OrdinalIgnoreCase))
        {
            return value / 100d;
        }

        return unit.Equals("nm", StringComparison.OrdinalIgnoreCase) ? value * 1e-9d : value;
    }

    private static string FindEdgeCasesGiePath()
    {
        string direct = Path.Combine(AppContext.BaseDirectory, "Fixtures", "gie", "proj-generated", "edge-cases.gie");
        if (File.Exists(direct))
        {
            return direct;
        }

        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null)
        {
            string candidate = Path.Combine(current.FullName, "test", "ProjNet.Tests", "Fixtures", "gie", "proj-generated", "edge-cases.gie");
            if (File.Exists(candidate))
            {
                return candidate;
            }

            current = current.Parent;
        }

        return default!;
    }
}
