<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1701;1702;1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="PublicApiGenerator" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ProjNet\ProjNET.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SRID.csv" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Generated\*.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Fixtures\gie\*.gie" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Fixtures\gigs\*.gie" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Fixtures\grids\*.*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Fixtures\defmodel\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Fixtures\tinshift\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
