// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 Martin Karing / TKI mbH, Chemnitz, Germany

namespace ProjNet.CoordinateSystems.Projections;

using System;
using System.Collections.Generic;
using ProjNet.CoordinateSystems.Transformations;

/// <summary>
/// Maintains a registry of supported projections keyed by their WKT or PROJ aliases.
/// </summary>
public partial class ProjectionsRegistry
{
    private static readonly Dictionary<Type, Func<IEnumerable<ProjectionParameter>, MathTransform>> BuiltInFactories =
        new()
        {
            [typeof(AdamsHemisphereInSquareProjection)] = static parameters => new AdamsHemisphereInSquareProjection(parameters),
            [typeof(AdamsWorldInSquare1Projection)] = static parameters => new AdamsWorldInSquare1Projection(parameters),
            [typeof(AdamsWorldInSquare2Projection)] = static parameters => new AdamsWorldInSquare2Projection(parameters),
            [typeof(AiroceanProjection)] = static parameters => new AiroceanProjection(parameters),
            [typeof(AiryProjection)] = static parameters => new AiryProjection(parameters),
            [typeof(AitoffProjection)] = static parameters => new AitoffProjection(parameters),
            [typeof(AlbersProjection)] = static parameters => new AlbersProjection(parameters),
            [typeof(ApianProjection)] = static parameters => new ApianProjection(parameters),
            [typeof(AugustProjection)] = static parameters => new AugustProjection(parameters),
            [typeof(AzimuthalEquidistantProjection)] = static parameters => new AzimuthalEquidistantProjection(parameters),
            [typeof(BaconProjection)] = static parameters => new BaconProjection(parameters),
            [typeof(Bertin1953Projection)] = static parameters => new Bertin1953Projection(parameters),
            [typeof(BipolarConicProjection)] = static parameters => new BipolarConicProjection(parameters),
            [typeof(BoggsProjection)] = static parameters => new BoggsProjection(parameters),
            [typeof(BonneProjection)] = static parameters => new BonneProjection(parameters),
            [typeof(CalCoFiProjection)] = static parameters => new CalCoFiProjection(parameters),
            [typeof(CassiniSoldnerProjection)] = static parameters => new CassiniSoldnerProjection(parameters),
            [typeof(CentralConicProjection)] = static parameters => new CentralConicProjection(parameters),
            [typeof(CentralCylindricalProjection)] = static parameters => new CentralCylindricalProjection(parameters),
            [typeof(ChamberlinTrimetricProjection)] = static parameters => new ChamberlinTrimetricProjection(parameters),
            [typeof(CollignonProjection)] = static parameters => new CollignonProjection(parameters),
            [typeof(ColombiaUrbanProjection)] = static parameters => new ColombiaUrbanProjection(parameters),
            [typeof(CompactMillerProjection)] = static parameters => new CompactMillerProjection(parameters),
            [typeof(CrasterProjection)] = static parameters => new CrasterProjection(parameters),
            [typeof(CylindricalEqualAreaProjection)] = static parameters => new CylindricalEqualAreaProjection(parameters),
            [typeof(DenoyerProjection)] = static parameters => new DenoyerProjection(parameters),
            [typeof(Eckert1Projection)] = static parameters => new Eckert1Projection(parameters),
            [typeof(Eckert2Projection)] = static parameters => new Eckert2Projection(parameters),
            [typeof(Eckert3Projection)] = static parameters => new Eckert3Projection(parameters),
            [typeof(Eckert4Projection)] = static parameters => new Eckert4Projection(parameters),
            [typeof(Eckert5Projection)] = static parameters => new Eckert5Projection(parameters),
            [typeof(Eckert6Projection)] = static parameters => new Eckert6Projection(parameters),
            [typeof(EqualEarthProjection)] = static parameters => new EqualEarthProjection(parameters),
            [typeof(EquidistantConicProjection)] = static parameters => new EquidistantConicProjection(parameters),
            [typeof(EquidistantCylindricalProjection)] = static parameters => new EquidistantCylindricalProjection(parameters),
            [typeof(EulerProjection)] = static parameters => new EulerProjection(parameters),
            [typeof(ExtendedTransverseMercator)] = static parameters => new ExtendedTransverseMercator(parameters),
            [typeof(FaheyProjection)] = static parameters => new FaheyProjection(parameters),
            [typeof(FoucautProjection)] = static parameters => new FoucautProjection(parameters),
            [typeof(FoucautSinusoidalProjection)] = static parameters => new FoucautSinusoidalProjection(parameters),
            [typeof(GallProjection)] = static parameters => new GallProjection(parameters),
            [typeof(GaussSchreiberTransverseMercatorProjection)] = static parameters => new GaussSchreiberTransverseMercatorProjection(parameters),
            [typeof(GeneralSinusoidalProjection)] = static parameters => new GeneralSinusoidalProjection(parameters),
            [typeof(GeostationarySatelliteProjection)] = static parameters => new GeostationarySatelliteProjection(parameters),
            [typeof(Ginsburg8Projection)] = static parameters => new Ginsburg8Projection(parameters),
            [typeof(GnomonicProjection)] = static parameters => new GnomonicProjection(parameters),
            [typeof(GoodeProjection)] = static parameters => new GoodeProjection(parameters),
            [typeof(GuyouProjection)] = static parameters => new GuyouProjection(parameters),
            [typeof(HammerProjection)] = static parameters => new HammerProjection(parameters),
            [typeof(HatanoProjection)] = static parameters => new HatanoProjection(parameters),
            [typeof(HealpixProjection)] = static parameters => new HealpixProjection(parameters),
            [typeof(HotineObliqueMercatorProjection)] = static parameters => new HotineObliqueMercatorProjection(parameters),
            [typeof(IghProjection)] = static parameters => new IghProjection(parameters),
            [typeof(InternationalMapWorldPolyconicProjection)] = static parameters => new InternationalMapWorldPolyconicProjection(parameters),
            [typeof(InterruptedGoodeHomolosineOceanicProjection)] = static parameters => new InterruptedGoodeHomolosineOceanicProjection(parameters),
            [typeof(InterruptedMollweideOceanicProjection)] = static parameters => new InterruptedMollweideOceanicProjection(parameters),
            [typeof(InterruptedMollweideProjection)] = static parameters => new InterruptedMollweideProjection(parameters),
            [typeof(IseaProjection)] = static parameters => new IseaProjection(parameters),
            [typeof(Kavrayskiy5Projection)] = static parameters => new Kavrayskiy5Projection(parameters),
            [typeof(Kavrayskiy7Projection)] = static parameters => new Kavrayskiy7Projection(parameters),
            [typeof(KrovakProjection)] = static parameters => new KrovakProjection(parameters),
            [typeof(LabordeProjection)] = static parameters => new LabordeProjection(parameters),
            [typeof(LagrangeProjection)] = static parameters => new LagrangeProjection(parameters),
            [typeof(LambertAzimuthalEqualAreaProjection)] = static parameters => new LambertAzimuthalEqualAreaProjection(parameters),
            [typeof(LambertConformalConic2SP)] = static parameters => new LambertConformalConic2SP(parameters),
            [typeof(LambertConformalConicAlternativeProjection)] = static parameters => new LambertConformalConicAlternativeProjection(parameters),
            [typeof(LambertEqualAreaConicProjection)] = static parameters => new LambertEqualAreaConicProjection(parameters),
            [typeof(LarriveeProjection)] = static parameters => new LarriveeProjection(parameters),
            [typeof(LaskowskiProjection)] = static parameters => new LaskowskiProjection(parameters),
            [typeof(LatLongProjection)] = static parameters => new LatLongProjection(parameters),
            [typeof(LeeOblatedStereographicProjection)] = static parameters => new LeeOblatedStereographicProjection(parameters),
            [typeof(LoximuthalProjection)] = static parameters => new LoximuthalProjection(parameters),
            [typeof(McBrydeThomasFlatPolarParabolicProjection)] = static parameters => new McBrydeThomasFlatPolarParabolicProjection(parameters),
            [typeof(McBrydeThomasFlatPolarQuarticProjection)] = static parameters => new McBrydeThomasFlatPolarQuarticProjection(parameters),
            [typeof(McBrydeThomasFlatPolarSineProjection)] = static parameters => new McBrydeThomasFlatPolarSineProjection(parameters),
            [typeof(McBrydeThomasFlatPolarSinusoidalProjection)] = static parameters => new McBrydeThomasFlatPolarSinusoidalProjection(parameters),
            [typeof(McBrydeThomasFlatPoleSineProjection)] = static parameters => new McBrydeThomasFlatPoleSineProjection(parameters),
            [typeof(Mercator)] = static parameters => new Mercator(parameters),
            [typeof(MercatorAuxiliarySphere)] = static parameters => new MercatorAuxiliarySphere(parameters),
            [typeof(MillerCylindricalProjection)] = static parameters => new MillerCylindricalProjection(parameters),
            [typeof(MillerOblatedStereographicProjection)] = static parameters => new MillerOblatedStereographicProjection(parameters),
            [typeof(ModifiedKrovakProjection)] = static parameters => new ModifiedKrovakProjection(parameters),
            [typeof(ModifiedStereographic48USProjection)] = static parameters => new ModifiedStereographic48USProjection(parameters),
            [typeof(ModifiedStereographic50USProjection)] = static parameters => new ModifiedStereographic50USProjection(parameters),
            [typeof(ModifiedStereographicAlaskaProjection)] = static parameters => new ModifiedStereographicAlaskaProjection(parameters),
            [typeof(MollweideProjection)] = static parameters => new MollweideProjection(parameters),
            [typeof(Murdoch1Projection)] = static parameters => new Murdoch1Projection(parameters),
            [typeof(Murdoch2Projection)] = static parameters => new Murdoch2Projection(parameters),
            [typeof(Murdoch3Projection)] = static parameters => new Murdoch3Projection(parameters),
            [typeof(NaturalEarth2Projection)] = static parameters => new NaturalEarth2Projection(parameters),
            [typeof(NaturalEarthProjection)] = static parameters => new NaturalEarthProjection(parameters),
            [typeof(NearSidedPerspectiveProjection)] = static parameters => new NearSidedPerspectiveProjection(parameters),
            [typeof(NellHammerProjection)] = static parameters => new NellHammerProjection(parameters),
            [typeof(NellProjection)] = static parameters => new NellProjection(parameters),
            [typeof(NewZealandMapGridProjection)] = static parameters => new NewZealandMapGridProjection(parameters),
            [typeof(NicolosiProjection)] = static parameters => new NicolosiProjection(parameters),
            [typeof(OblatedEqualAreaProjection)] = static parameters => new OblatedEqualAreaProjection(parameters),
            [typeof(ObliqueCylindricalEqualAreaProjection)] = static parameters => new ObliqueCylindricalEqualAreaProjection(parameters),
            [typeof(ObliqueMercatorProjection)] = static parameters => new ObliqueMercatorProjection(parameters),
            [typeof(ObliqueStereographicProjection)] = static parameters => new ObliqueStereographicProjection(parameters),
            [typeof(OrteliusProjection)] = static parameters => new OrteliusProjection(parameters),
            [typeof(OrthographicProjection)] = static parameters => new OrthographicProjection(parameters),
            [typeof(PattersonProjection)] = static parameters => new PattersonProjection(parameters),
            [typeof(PconicProjection)] = static parameters => new PconicProjection(parameters),
            [typeof(PeirceQuincuncialProjection)] = static parameters => new PeirceQuincuncialProjection(parameters),
            [typeof(PolarStereographicProjection)] = static parameters => new PolarStereographicProjection(parameters),
            [typeof(PolyconicProjection)] = static parameters => new PolyconicProjection(parameters),
            [typeof(PseudoMercator)] = static parameters => new PseudoMercator(parameters),
            [typeof(PutninsP1Projection)] = static parameters => new PutninsP1Projection(parameters),
            [typeof(PutninsP2Projection)] = static parameters => new PutninsP2Projection(parameters),
            [typeof(PutninsP3PrimeProjection)] = static parameters => new PutninsP3PrimeProjection(parameters),
            [typeof(PutninsP3Projection)] = static parameters => new PutninsP3Projection(parameters),
            [typeof(PutninsP4PProjection)] = static parameters => new PutninsP4PProjection(parameters),
            [typeof(PutninsP5PrimeProjection)] = static parameters => new PutninsP5PrimeProjection(parameters),
            [typeof(PutninsP5Projection)] = static parameters => new PutninsP5Projection(parameters),
            [typeof(PutninsP6PrimeProjection)] = static parameters => new PutninsP6PrimeProjection(parameters),
            [typeof(PutninsP6Projection)] = static parameters => new PutninsP6Projection(parameters),
            [typeof(QuadrilateralizedSphericalCubeProjection)] = static parameters => new QuadrilateralizedSphericalCubeProjection(parameters),
            [typeof(QuarticAuthalicProjection)] = static parameters => new QuarticAuthalicProjection(parameters),
            [typeof(RectangularPolyconicProjection)] = static parameters => new RectangularPolyconicProjection(parameters),
            [typeof(RobinsonProjection)] = static parameters => new RobinsonProjection(parameters),
            [typeof(RoussilheStereographicProjection)] = static parameters => new RoussilheStereographicProjection(parameters),
            [typeof(S2Projection)] = static parameters => new S2Projection(parameters),
            [typeof(SchMathTransform)] = static parameters => new SchMathTransform(AsProjectionParameterList(parameters)),
            [typeof(SinusoidalProjection)] = static parameters => new SinusoidalProjection(parameters),
            [typeof(SpaceObliqueMercatorProjection)] = static parameters => new SpaceObliqueMercatorProjection(parameters),
            [typeof(SpilhausProjection)] = static parameters => new SpilhausProjection(parameters),
            [typeof(SwissObliqueMercatorProjection)] = static parameters => new SwissObliqueMercatorProjection(parameters),
            [typeof(TimesProjection)] = static parameters => new TimesProjection(parameters),
            [typeof(TissotProjection)] = static parameters => new TissotProjection(parameters),
            [typeof(ToblerMercatorProjection)] = static parameters => new ToblerMercatorProjection(parameters),
            [typeof(TransverseCentralCylindricalProjection)] = static parameters => new TransverseCentralCylindricalProjection(parameters),
            [typeof(TransverseCylindricalEqualAreaProjection)] = static parameters => new TransverseCylindricalEqualAreaProjection(parameters),
            [typeof(TransverseMercator)] = static parameters => new TransverseMercator(parameters),
            [typeof(TwoPointEquidistantProjection)] = static parameters => new TwoPointEquidistantProjection(parameters),
            [typeof(UpsProjection)] = static parameters => new UpsProjection(parameters),
            [typeof(Urmaev5Projection)] = static parameters => new Urmaev5Projection(parameters),
            [typeof(UrmaevFlatPolarSinusoidalProjection)] = static parameters => new UrmaevFlatPolarSinusoidalProjection(parameters),
            [typeof(VanDerGrinten2Projection)] = static parameters => new VanDerGrinten2Projection(parameters),
            [typeof(VanDerGrinten3Projection)] = static parameters => new VanDerGrinten3Projection(parameters),
            [typeof(VanDerGrinten4Projection)] = static parameters => new VanDerGrinten4Projection(parameters),
            [typeof(VanDerGrintenProjection)] = static parameters => new VanDerGrintenProjection(parameters),
            [typeof(Vitkovsky1Projection)] = static parameters => new Vitkovsky1Projection(parameters),
            [typeof(Wagner1Projection)] = static parameters => new Wagner1Projection(parameters),
            [typeof(Wagner2Projection)] = static parameters => new Wagner2Projection(parameters),
            [typeof(Wagner3Projection)] = static parameters => new Wagner3Projection(parameters),
            [typeof(Wagner4Projection)] = static parameters => new Wagner4Projection(parameters),
            [typeof(Wagner5Projection)] = static parameters => new Wagner5Projection(parameters),
            [typeof(Wagner6Projection)] = static parameters => new Wagner6Projection(parameters),
            [typeof(Wagner7Projection)] = static parameters => new Wagner7Projection(parameters),
            [typeof(WerenskioldProjection)] = static parameters => new WerenskioldProjection(parameters),
            [typeof(Winkel1Projection)] = static parameters => new Winkel1Projection(parameters),
            [typeof(Winkel2Projection)] = static parameters => new Winkel2Projection(parameters),
            [typeof(WinkelTripelProjection)] = static parameters => new WinkelTripelProjection(parameters),
        };
}
