<?xml version="1.0" encoding="utf-8"?>
<Project>

  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Assembly Info">
    <Company>NetTopologySuite - Team</Company>

    <CopyrightPeople>$(Company)</CopyrightPeople>
    <CopyrightPeople>$(CopyrightPeople), Morten Nielsen</CopyrightPeople>
    <!--<CopyrightPeople>$(CopyrightPeople), Additional Person</CopyrightPeople>-->
    <Copyright>Copyright © 2006 - $([System.DateTime]::UtcNow.Year) $(CopyrightPeople)</Copyright>
  </PropertyGroup>

  <PropertyGroup Label="SourceLink Info">
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

</Project>
